mysite/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
        url(r'^register/$', views.register, name='register'),
        url(r"logout/$", views.logout_view, name="logout"),
        url(r'^login/$', views.login_view, name='login'),
        url(r'^profile/$', views.my_profile, name='profile'),
        url(r'^edit/$', views.edit_profile, name='edit'),
        url(r'^change-password/$', views.change_password, name='change_password'),
        url(r'^change-avatar/$', views.change_avatar, name='change_avatar'),
        url(r'^change-skills/$', views.change_skills, name='change_skills'),
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomeView.as_view(), name="home"),
    url(r'^accounts/', include("accounts.urls", namespace="accounts")),
    url(r'^accounts/', include("django.contrib.auth.urls")),
    url(r'^projects/', include("projects.urls", namespace="projects")),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/projects/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"new/$", views.ProjectCreate.as_view(), name="new_project"),
    url(r"detail/(?P<project_pk>\d+)/$", views.project_detail, name="project_detail"),
    url(r"detail/(?P<project_pk>\d+)/add/postion$", views.add_position, name="position_create"),
    url(r"edit/(?P<pk>\d+)/$", views.EditProject.as_view(), name="edit_project"),
    url(r"^delete/(?P<pk>\d+)/$", views.DeleteProject.as_view(), name="delete_project"),
    url(r"^apply/(?P<position_pk>\d+)/$", views.ApplyView.as_view(), name="apply"),
    url(r"applications/$", views.applications, name="applications"),
    url(r"applications/accepted/$", views.accepted_applications, name="accepted_applications"),
    url(r"applications/rejected/$", views.rejected_applications, name="rejected_applications"),
    url(r"applications/(?P<app_pk>\d+)/(?P<status>accepted|rejected)/$", views.accept_or_reject, name="accept_reject"),
    url(r"notifications/$", views.new_notifications, name="notifications"),
    url(r"search/skill/(?P<skill>[a-zA-Z]+)/$", views.by_skill, name="by_skill"),
    url(r"search/projects/all/$", views.all_projects, name="all_projects"),
    url(r"search/$", views.by_keyword, name="search"),
]

mysite/templates/layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>

  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  <title>Circle</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FONTS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>

  <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="stylesheet" href="{% static 'css/global.css' %}">

  <!-- JS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
  <script type="text/javascript" src="{% static 'js/autogrow.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/global.js' %}"></script>




</head>
<body>
  <header class="circle--header">
    <div class="bounds">
      <div class="circle--fluid">
        <div class="circle--fluid--cell">
          <h1 class="hide-text circle--logo"><a class="logo" href="{% url 'home' %}">Circle</a></h1>
        </div>
        <div class="circle--fluid--cell circle--fluid--primary">
            <p></p>
          <div class="circle--search">
            <form method="GET" action="{% url 'projects:search' %}">
              <input type="text" name="q" placeholder="Search Projects..." />
               <button>
              <svg version="1.1" class="search" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 12 12" xml:space="preserve">
                <path d="M12,10.6L8.3,6.9C8.7,6.2,9,5.4,9,4.5C9,2,7,0,4.5,0S0,2,0,4.5S2,9,4.5,9c0.9,0,1.7-0.3,2.4-0.7l3.7,3.7L12,10.6z M2,4.5
                C2,3.1,3.1,2,4.5,2S7,3.1,7,4.5C7,5.9,5.9,7,4.5,7S2,5.9,2,4.5z"/>
              </svg>
            </button>
            </form>
          </div>
        </div>
        <div class="circle--fluid--cell circle--fluid--secondary">
          <nav>
            <ul class="circle--inline">
                {% if user.is_authenticated %}
                <li><a href="{% url 'accounts:logout' %}">Sign Out</a></li>
                <li><a href="{% url 'accounts:profile' %}">My Profile</a></li>
                <li><a href="{% url 'projects:notifications' %}">Notifications ({{ user.notifications.unread.count }})</a></li>
                {% else %}
              <li><a href="{% url 'accounts:register' %}">Sign Up</a></li>
              <li><a href="{% url 'accounts:login' %}">Sign In</a></li>
                {% endif %}
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </header>
{% block content %}{% endblock content %}
</body>
</html>

mysite/templates/login.html
{% extends "layout.html" %}

{% block content %}
  <div class="bounds">
    <div class="grid-50 centered">
      <h2>Sign In</h2>
      <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Login">
      </form>
    </div>
  </div>
{% endblock %}

mysite/templates/signin.html
{% extends "layout.html" %}

{% block content %}
  <div class="bounds">
    <div class="grid-30 centered">
      <h2>Sign In</h2>
    </div>
  </div>
{% endblock %}