mysite/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
        url(r'^register/$', views.register, name='register'),
        url(r"logout/$", views.logout_view, name="logout"),
        url(r'^login/$', views.login_view, name='login'),
        url(r'^profile/$', views.my_profile, name='profile'),
        url(r'^edit/$', views.edit_profile, name='edit'),
        url(r'^change-password/$', views.change_password, name='change_password'),
        url(r'^change-avatar/$', views.change_avatar, name='change_avatar'),
        url(r'^change-skills/$', views.change_skills, name='change_skills'),
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomeView.as_view(), name="home"),
    url(r'^accounts/', include("accounts.urls", namespace="accounts")),
    url(r'^accounts/', include("django.contrib.auth.urls")),
    url(r'^projects/', include("projects.urls", namespace="projects")),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/projects/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"new/$", views.ProjectCreate.as_view(), name="new_project"),
    url(r"detail/(?P<project_pk>\d+)/$", views.project_detail, name="project_detail"),
    url(r"detail/(?P<project_pk>\d+)/add/postion$", views.add_position, name="position_create"),
    url(r"edit/(?P<pk>\d+)/$", views.EditProject.as_view(), name="edit_project"),
    url(r"^delete/(?P<pk>\d+)/$", views.DeleteProject.as_view(), name="delete_project"),
    url(r"^apply/(?P<position_pk>\d+)/$", views.ApplyView.as_view(), name="apply"),
    url(r"applications/$", views.applications, name="applications"),
    url(r"applications/accepted/$", views.accepted_applications, name="accepted_applications"),
    url(r"applications/rejected/$", views.rejected_applications, name="rejected_applications"),
    url(r"applications/(?P<app_pk>\d+)/(?P<status>accepted|rejected)/$", views.accept_or_reject, name="accept_reject"),
    url(r"notifications/$", views.new_notifications, name="notifications"),
    url(r"search/skill/(?P<skill>[a-zA-Z]+)/$", views.by_skill, name="by_skill"),
    url(r"search/projects/all/$", views.all_projects, name="all_projects"),
    url(r"search/$", views.by_keyword, name="search"),
]

mysite/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from multiselectfield import MultiSelectField

SKILL_CHOICES = (
        ('android', "Android Developer"),
        ('designer', "Designer"),
        ('java', "Java Developer"),
        ('php', "PHP Developer"),
        ('python', "Python Developer"),
        ('rails', "Rails Developer"),
        ('wordpress', "Wordpress Devloper"),
        ('ios', "iOS Developer")
    )


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.CharField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    avatar = models.ImageField(upload_to='images/', blank=True)
    skills = MultiSelectField(choices=SKILL_CHOICES)


@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_profile(sender, instance, **kwargs):
    instance.profile.save()

mysite/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User

from .models import Profile


class SignUpForm(UserCreationForm):
    birth_date = forms.DateField(help_text='Required. Format: YYYY-MM-DD')
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    class Meta:
        model = User
        fields = ('username', 'birth_date', 'first_name', 'last_name',
                  'password1', 'password2',)


class EditProfileForm(UserChangeForm):
    def __init__(self, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        del self.fields['password']

    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    email = forms.EmailField(required=False)

    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'email', 'password',)


class AvatarForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ('avatar', )


class SkillForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ('skills', )

mysite/accounts/views.py
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash, logout
from django.contrib.auth.decorators import login_required

from .models import Profile
from .forms import EditProfileForm, AvatarForm, SkillForm, SignUpForm

from projects.models import Project


def register(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()  # load the profile instance created by the signal
            user.profile.birth_date = form.cleaned_data.get('birth_date')
            user.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = SignUpForm()
    return render(request, 'register.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('home')


def login_view(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            if form.user_cache is not None:
                user = form.user_cache
                if user.is_active:
                    login(request, user)
                    return redirect('home')
                else:
                    messages.error(request, "That user account has been disabled." )
            else:
                messages.error(request, "Username or password is incorrect.")
    return render(request, 'login.html', {'form': form})


def my_profile(request):
    """Shows the users profile, shows users projects and skills"""
    profile = Profile.objects.get(user=request.user)
    projects = Project.objects.filter(owner=request.user)
    return render(request, 'profile.html', {'profile': profile, 'projects': projects})


@login_required
def edit_profile(request):
    """Allows user to edit their email or name"""
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user, files=request.FILES)

        if form.is_valid():
            form.save()
            return redirect('/accounts/profile')

    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'edit_profile.html', args)


@login_required
def change_password(request):
    """Allows user to change their password"""
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Your password was successfully updated!')
            return redirect('/accounts/profile')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'change_password.html', {'form': form})


@login_required
def change_avatar(request):
    """Allows user to upload and save a avatar"""
    if request.method == 'POST':
        form = AvatarForm(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid():
            form.save()
            return redirect('/accounts/profile')
    else:
        form = AvatarForm()
    return render(request, 'change_avatar.html', {
        'form': form
    })


@login_required
def change_skills(request):
    """Allows user to select their skills from a drop down menu"""
    if request.method == 'POST':
        form = SkillForm(request.POST, instance=request.user.profile)
        if form.is_valid():
            form.save()
            return redirect('/accounts/profile')
    else:
        form = SkillForm()
    return render(request, 'skills.html', {
        'form': form
    })

mysite/accounts/templates/change_avatar.html
{% extends 'layout.html' %}

{% block content %}
    <div class="grid-75">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
            <a class="selected" href="{% url 'accounts:profile' %}">Cancel</a>
        </form>
    </div>
{% endblock %}

mysite/accounts/templates/change_password.html
{% extends 'layout.html' %}

{% block content %}
    <div class="grid-75">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
        </form>
    </div>
{% endblock %}

mysite/accounts/templates/edit_profile.html
{% extends 'layout.html' %}

{% block content %}
    <div class="grid-75">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
        </form>
    </div>
{% endblock %}

mysite/accounts/templates/index.html
{% extends 'layout.html' %}

{% block content %}
    <h1></h1>
{% endblock %}

mysite/accounts/templates/login.html
{% extends "layout.html" %}

{% block content %}
<form method="POST" action="{% url 'accounts:login' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="button-primary" value="Sign In">
</form>
{% endblock %}

mysite/accounts/templates/profile.html
{% extends "layout.html" %}
{% load static from staticfiles %}
{% block content %}
<body>
  <div class="circle--actions--bar">
    <nav class="bounds">
      <ul class="circle--pill--list">
        <li><a href="{% url 'projects:applications' %}">Applications</a></li>
        <li><a class="selected" href="{% url 'accounts:profile' %}">Profile</a></li>
      </ul>
    </nav>
  </div>

  <div class="bounds circle--page">
    <div class="circle--page--header circle--fluid">
      <div class="circle--fluid--cell circle--fluid--primary">
      </div>
      <div class="circle--fluid--cell circle--fluid--secondary">
        <a class="button icon-on-left" href="{% url 'accounts:edit' %}">Edit</a>
        <a class="button icon-on-left" href="{% url 'accounts:change_avatar' %}">Change Avatar</a>
        <a class="button icon-on-left" href="{% url 'accounts:change_skills' %}">Add Skills</a>
        <a class="button icon-on-left" href="{% url 'projects:new_project' %}">Create Project</a>
      </div>
    </div>

    <div class="grid-70">
      <h1>{{ user.username }}'s Profile</h1>
        <h3> {{ user.first_name }} {{user.last_name }}</h3>
      <div class="circle--article--body">
          <p>Contact Email: {{ user.email }}</p>



        <p></p>
      </div>
        <h2>Past Projects</h2>
      <table class="u-full-width circle--table">
        <thead>
          <tr>
            <th>Project Title</th>
          </tr>
        </thead>
        </tbody>
        </table>
        </tbody>
      {% if projects %}
          {% for project in projects %}
            <ul><a href="{% url 'projects:project_detail' project_pk=project.id %}">{{ project.title }}</a></ul>
          {% endfor %}
       {% else %}
          <p>There are none</p>
       {% endif %}
    </div>

    <div class="grid-25 grid-push-5">

      <div class="circle--secondary--module">
        <div class="circle--primary--avatar">
          {% if profile.avatar %}
            <img src="{{ profile.avatar.url }}">
          {% else %}
            <ul>No Avatar</ul>
          {% endif %}
        </div>
      </div>

      <div class="circle--secondary--module">
        <h4>My Skills</h4>
        <ul class="unloaded">
            {% if profile.skills %}
              <ul>{{ profile.skills }}</ul>
            {% else %}
              <td>None</td>
            {% endif %}
        </ul>
      </div>
      <div class="circle--secondary--module">
        <h4>My Projects</h4>
      {% if projects %}
        <ul class="circle--link--list">
          {% for project in projects %}
            <li><a href="{% url 'projects:project_detail' project_pk=project.id %}">{{ project.title }}</a></li>
          {% endfor %}
       {% else %}
          <p>There are none</p>
       {% endif %}
        </ul>
      </div>
    </div>

  </div>
</body>
{% endblock content %}

mysite/accounts/templates/register.html
{% extends "layout.html" %}

{% block content %}
  <div class="bounds">
    <div class="grid-50 centered">
      <h2>Register</h2>
      <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
      </form>
    </div>
  </div>
{% endblock %}

mysite/accounts/templates/skills.html
{% extends 'layout.html' %}

{% block content %}
    <div class="grid-75">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
             <a class="selected" href="{% url 'accounts:profile' %}">Cancel</a>
        </form>
    </div>
{% endblock %}