mysite/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
        url(r'^register/$', views.register, name='register'),
        url(r"logout/$", views.logout_view, name="logout"),
        url(r'^login/$', views.login_view, name='login'),
        url(r'^profile/$', views.my_profile, name='profile'),
        url(r'^edit/$', views.edit_profile, name='edit'),
        url(r'^change-password/$', views.change_password, name='change_password'),
        url(r'^change-avatar/$', views.change_avatar, name='change_avatar'),
        url(r'^change-skills/$', views.change_skills, name='change_skills'),
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomeView.as_view(), name="home"),
    url(r'^accounts/', include("accounts.urls", namespace="accounts")),
    url(r'^accounts/', include("django.contrib.auth.urls")),
    url(r'^projects/', include("projects.urls", namespace="projects")),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/projects/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"new/$", views.ProjectCreate.as_view(), name="new_project"),
    url(r"detail/(?P<project_pk>\d+)/$", views.project_detail, name="project_detail"),
    url(r"detail/(?P<project_pk>\d+)/add/postion$", views.add_position, name="position_create"),
    url(r"edit/(?P<pk>\d+)/$", views.EditProject.as_view(), name="edit_project"),
    url(r"^delete/(?P<pk>\d+)/$", views.DeleteProject.as_view(), name="delete_project"),
    url(r"^apply/(?P<position_pk>\d+)/$", views.ApplyView.as_view(), name="apply"),
    url(r"applications/$", views.applications, name="applications"),
    url(r"applications/accepted/$", views.accepted_applications, name="accepted_applications"),
    url(r"applications/rejected/$", views.rejected_applications, name="rejected_applications"),
    url(r"applications/(?P<app_pk>\d+)/(?P<status>accepted|rejected)/$", views.accept_or_reject, name="accept_reject"),
    url(r"notifications/$", views.new_notifications, name="notifications"),
    url(r"search/skill/(?P<skill>[a-zA-Z]+)/$", views.by_skill, name="by_skill"),
    url(r"search/projects/all/$", views.all_projects, name="all_projects"),
    url(r"search/$", views.by_keyword, name="search"),
]

mysite/projects/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from multiselectfield import MultiSelectField

# Create your models here.
SKILL_CHOICES = (
        ('android', "Android Developer"),
        ('designer', "Designer"),
        ('java', "Java Developer"),
        ('php', "PHP Developer"),
        ('python', "Python Developer"),
        ('rails', "Rails Developer"),
        ('wordpress', "Wordpress Devloper"),
        ('ios', "iOS Developer")
    )


class Project(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL)
    title = models.CharField(max_length=35, default='')
    description = models.TextField(default='')
    requirements = models.TextField(default='')
    timeline = models.TextField(default='')
    skills = MultiSelectField(choices=SKILL_CHOICES)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('projects:project_detail', kwargs={'project_pk': self.id})


class Position(models.Model):
    project = models.ForeignKey(Project, default='', related_name='positions')
    name = models.CharField(max_length=35, default='')
    description = models.TextField(default='')
    skills = MultiSelectField(choices=SKILL_CHOICES)

    def __str__(self):
        return self.name


class Application(models.Model):
    APP_STATUS = (
        ('p', 'Pending'),
        ('a', 'Accepted'),
        ('r', 'Rejected'),
    )
    position = models.ForeignKey(Position, on_delete=models.CASCADE)
    applicant = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="applications")
    status = models.CharField(max_length=1, choices=APP_STATUS, default='p')

mysite/projects/forms.py
from django import forms

from .models import Position, Project, Application


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'description', 'timeline', 'requirements', 'skills', ]


class PositionForm(forms.ModelForm):

    class Meta:
        model = Position
        fields = ['name', 'description', 'skills', ]


class ApplicationForm(forms.ModelForm):

    class Meta:
        model = Application
        fields = ('applicant', 'position', 'status')
        widgets = {'applicant': forms.HiddenInput,
                   'position': forms.HiddenInput,
                   'status': forms.HiddenInput}

mysite/projects/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from notifications.signals import notify

from django.views.generic import (
    CreateView,
    UpdateView,
    DeleteView,
)

from .models import Project, Position, Application
from .forms import ProjectForm, PositionForm, ApplicationForm
from accounts.models import Profile


skill = ['Android Developer', 'Designer', 'Java Developer', 'PHP Developer', 'Python Developer',
          'Rails Developer', 'Wordpress Devloper', 'iOS Developer',]


class ProjectCreate(LoginRequiredMixin, CreateView):
    form_class = ProjectForm
    template_name = "new_project.html"
    queryset = Project.objects.all()

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(ProjectCreate, self).form_valid(form)


class EditProject(LoginRequiredMixin, UpdateView):
    model = Project
    fields = ['title', 'description', 'requirements', 'timeline', 'skills',]

    def form_valid(self, form):
        if form.instance.owner == self.request.user:
            return super(EditProject, self).form_valid(form)


class DeleteProject(LoginRequiredMixin, DeleteView):
    model = Project
    success_url = reverse_lazy("home")


def project_detail(request, project_pk):
    project = Project.objects.get(id=project_pk)
    position = project.positions.all()
    return render(request, 'project_detail.html', {'project': project, 'position': position})


@login_required
def add_position(request, project_pk):
    project = Project.objects.get(id=project_pk)
    if request.method == 'POST':
        form = PositionForm(request.POST)
        if form.is_valid():
            position = form.save(commit=False)
            position.project = project
            position.save()
            return redirect('projects:project_detail', project_pk=project.id)
    else:
        form = PositionForm()
        args = {'form': form}
    return render(request, 'new_position.html', args)


class ApplyView(LoginRequiredMixin, CreateView):
    form_class = ApplicationForm
    model = Application
    template_name = "new_app.html"
    success_url = reverse_lazy("home")

    def get_initial(self, **kwargs):
        return {'position': self.kwargs.get('position_pk'),
                'applicant': self.request.user,
                'status': 'p'}

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(ApplyView, self).form_valid(form)


@login_required
def applications(request):
    application = Application.objects.filter(position__project__owner=request.user)
    return render(request, 'applications.html', {'application': application})


@login_required
def accepted_applications(request):
    application = Application.objects.filter(position__project__owner=request.user, status='a')
    return render(request, 'accepted_applications.html', {'application': application})


@login_required
def rejected_applications(request):
    application = Application.objects.filter(position__project__owner=request.user, status='r')
    return render(request, 'rejected_applications.html', {'application': application})


@login_required
def accept_or_reject(request, app_pk, status):
    application = Application.objects.get(id=app_pk)
    position = Position.objects.get(application__id=application.id)
    if status == "accepted":
        application.status = "a"
        application.save()
        position.filled = True
        position.save()
        notify.send(request.user, recipient=application.applicant,
            verb="{} accepted you for the position '{}'.".format(
                request.user,
                application.position.name
            )
        )
        return HttpResponseRedirect(reverse('home'))
    if status == "rejected":
        application.status = "r"
        application.save()
        position.filled = True
        position.save()
        notify.send(request.user, recipient=application.applicant,
            verb="{} rejected you for the position '{}'.".format(
                 request.user,
                application.position.name
             )
        )
        return HttpResponseRedirect(reverse('home'))


@login_required
def new_notifications(request):
    unread_notifications = request.user.notifications.unread()
    unread_notification_count = request.user.notifications.unread().count()
    return render(request, 'notifications.html',
                  {'unread_notifications': unread_notifications,
                   'unread_notification_count': unread_notification_count
                   })


def all_projects(request):
    projects = Project.objects.all()
    return render(request, 'all_projects.html', {'projects': projects})


def by_skill(request, skill):
    projects = Project.objects.filter(Q(skills__icontains=skill))
    return render(request, "search.html", {'projects': projects})


def by_keyword(request):
    query = request.GET.get('q', '')
    all_projects = Project.objects.all()
    projects = all_projects.filter(
        Q(description__icontains=query) | Q(title__icontains=query)
    )
    return render(request, "search.html", {'projects': projects, 'all_projects': all_projects})

mysite/projects/templates/accepted_applications.html
{% extends "layout.html" %}
{% block content %}


  <div class="circle--actions--bar">
    <nav class="bounds">
      <ul class="circle--pill--list">
        <li><a class="selected" href="{% url 'projects:applications' %}">Applications</a></li>
        <li><a href="{% url 'accounts:profile' %}">Profile</a></li>
      </ul>
    </nav>
  </div>

  <div class="bounds circle--page">
    <div class="circle--page--header grid-100">
      <h2>Applications</h2>
    </div>

    <div class="grid-25">
      <div class="circle--filter circle--secondary--module">
        <h4>Status</h4>
        <ul class="circle--filter--list">
          <a href="{% url 'projects:applications' %}">All Applications</a>
        </ul>
         <ul class="circle--filter--list">
          <a class="selected" href="{% url 'projects:accepted_applications' %}">Accepted</a>
           <p></p>
          <a href="{% url 'projects:rejected_applications' %}">Rejected</a>
        </ul>
      </div>
    </div>

    <div class="grid-70 grid-push-5">
      <table class="u-full-width circle--table">
        <thead>
          <tr>
            <th>Applicant</th>
            <th class="circle--cell--right">Applicant Position</th>
          </tr>
        </thead>
        <tbody>
          {% if application %}
            {% for application in application %}
              {% if application.status == 'a' %}
              <td><h3><a>{{ application.applicant.first_name }}</a></h3>
              <td class="circle--cell--right"><span class="secondary-label"></span>
              <h3>{{ application.position }}</h3>
              <td class="circle--cell--right"><span class="secondary-label"></span>
              <a href="{% url 'projects:accept_reject' app_pk=application.pk status='accepted' %}"></a>
              <a href="{% url 'projects:accept_reject' app_pk=application.pk status='rejected' %}"></a>
              {% endif %}
              </tr>
            {% endfor %}
          {% else %}
            <p>You have not approved any applications</p>
          {% endif %}
        </tbody>
      </table>

    </div>

  </div>
</body>
</html>
{% endblock %}

mysite/projects/templates/all_projects.html
{% extends "layout.html" %}
{% load static from staticfiles %}


{% block content %}
<div class="circle--actions--bar">
    <nav class="bounds">
      <ul class="circle--pill--list">
          <h2>Search Results:</h2>
      </ul>
    </nav>
  </div>
  <div class="bounds circle--page">
    <div class="grid-70">
      <div class="circle--article--body">
        {% if projects %}
          {% for project in projects %}
            <h3><a href="{% url 'projects:project_detail' project_pk=project.id %}">{{ project.title }}</a></h3>
            <h4>Project Description:</h4>
            <p>{{ project.description }}</p>
            <hr>
          {% endfor %}
        {% else %}
        <p>There were no results for that search!</p>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

mysite/projects/templates/applications.html
{% extends "layout.html" %}
{% block content %}


  <div class="circle--actions--bar">
    <nav class="bounds">
      <ul class="circle--pill--list">
        <li><a class="selected" href="{% url 'projects:applications' %}">Applications</a></li>
        <li><a href="{% url 'accounts:profile' %}">Profile</a></li>
      </ul>
    </nav>
  </div>

  <div class="bounds circle--page">
    <div class="circle--page--header grid-100">
      <h2>Applications</h2>
    </div>

    <div class="grid-25">
      <div class="circle--filter circle--secondary--module">
        <h4>Status</h4>
        <ul class="circle--filter--list">
          <li><a class="selected">All Applications</a></li>
          <p></p>
          <a href="{% url 'projects:accepted_applications' %}">Accepted</a>
          <p></p>
          <a href="{% url 'projects:rejected_applications' %}">Rejected</a>
        </ul>
      </div>
    </div>

    <div class="grid-70 grid-push-5">
      <table class="u-full-width circle--table">
        <thead>
          <tr>
            <th>Applicant</th>
            <th class="circle--cell--right">Applicant Position</th>
          </tr>
        </thead>
        <tbody>
          {% if application %}
            {% for application in application %}
              {% if application.status == 'p' %}
              <td><h3><a>{{ application.applicant.first_name }}</a></h3>
              <td class="circle--cell--right"><span class="secondary-label"></span>
              <h3>{{ application.position }}</h3>
              <td class="circle--cell--right"><span class="secondary-label"></span>
              <button><a href="{% url 'projects:accept_reject' app_pk=application.pk status='accepted' %}">Accept</a></button>
              <button><a href="{% url 'projects:accept_reject' app_pk=application.pk status='rejected' %}">Reject</a></button>
              {% endif %}
              </tr>
            {% endfor %}
          {% else %}
            <p>No one has applied to any positions</p>
          {% endif %}
        </tbody>
      </table>

    </div>

  </div>
</body>
</html>
{% endblock %}

mysite/projects/templates/edit_project.html
{% extends 'layout.html' %}

{% block content %}
    <div class="grid-75">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
        </form>
    </div>
{% endblock %}

mysite/projects/templates/new_app.html
{% extends "layout.html" %}
{% block content %}
<form action="" method="post">
{% csrf_token %}
{{ form }}
<div class="circle--actions--bar">
  <div class="bounds">
    <div class="grid-100">
      <p>Are you sure you want to apply for the position of {{ position_name }}?</p>
      <input type="submit" class="button button-primary" value="Yes">
      <a class="button button-text" href="{% url 'accounts:profile' %}">Cancel</a>
    </div>
  </div>
</div>
{% endblock %}

mysite/projects/templates/new_position.html
{% extends 'layout.html' %}

{% block content %}
  <div class="bounds">
    <div class="grid-50 centered">
      <h2>New Position</h2>
      <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
      </form>
    </div>
  </div>
{% endblock %}

mysite/projects/templates/new_project.html
{% extends "layout.html" %}
{% block content %}
  <div class="bounds">
    <div class="grid-50 centered">
      <h2>New Project</h2>
      <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
      </form>
    </div>
  </div>
{% endblock %}

mysite/projects/templates/notifications.html
{% extends "layout.html" %}

{% block content %}

<div class="circle--actions--bar">
    <nav class="bounds">
      <ul class="circle--pill--list">
          <h2>Recent Notifications</h2>
      </ul>
    </nav>
  </div>

  <div class="bounds circle--page">
    <div class="grid-70">
      <div class="circle--article--body">
      {% if unread_notifications %}
        {% for message in unread_notifications %}
            <p>{{ message.verb }}</p>
            <p><strong>{{ message.timestamp}}</strong></p>
            <hr/>
          {% endfor %}
      {% else %}
          <p>You do not have any Notifications!</p>
      {% endif %}
      </div>
    </div>
  </div>

{% endblock %}

mysite/projects/templates/project_detail.html
{% extends "layout.html" %}

{% block content %}

<div class="circle--actions--bar">
    <div class="bounds">
      <div class="grid-100">
        {% if request.user == project.owner %}
        <a class="button" href="{% url 'projects:edit_project' pk=project.id %}">Edit Project</a>
        <a class="button" href="{% url 'projects:delete_project' pk=project.id %}">Delete Project</a>
        <a class="button" href="{% url 'projects:position_create' project_pk=project.id %}">New Position</a>
        <a class="button" href="{% url 'accounts:profile' %}">Looks good!</a>
        {% endif %}
      </div>
    </div>
  </div>

  <div class="bounds circle--page circle--article">
    <div class="grid-70">
      <div class="circle--article--header">
        <h4 class="circle--article--section">Offered By: {{ project.owner }}</h4>
        <h4 class="circle--article--section">Project</h4>
        <h1 class="circle--article--title">{{ project.title }}</h1>
      </div>

      <div class="circle--article--body">
        <h3>Description</h3>
        <p>{{ project.description }}</p>
      </div>

      <div class="circle--article--body">
        <h3>Requirements</h3>
        <p>{{ project.requirements }}</p>
      </div>

      <div class="circle--article--body">
        <h3>Timeline</h3>
          <p>{{ project.timeline }}</p>
      </div>

      <div class="circle--article--body">
        <h3>Skills Required</h3>
        <p>{{ project.skills }}</p>
      </div>

      <div class="circle--project--positions">
        <h3>Positions</h3>

        {% if position %}
        <ul class="circle--group--list">
           {% for position in position %}
            <li>
              <h3>{{ position.name }}</h3>
              <p>
                Description: {{ position.description }}
              </p>
              <p>
                Skill required: {{ position.skills }}
              </p>
              {% if request.user != project.owner %}
              <a class="button button-primary" href="{% url 'projects:apply' position_pk=position.id %}">Apply</a>
              {% endif %}
            </li>
          {% endfor %}
        </ul>
        {% else %}
        <p>There are no positions for this project yet</p>
        {% endif %}
      </div>


    </div>
  </div>
{% endblock %}

mysite/projects/templates/projects.html
{% extends "layout.html" %}
{% load static from staticfiles %}

{% block content %}

  <div class="bounds circle--page">
    <div class="circle--page--header circle--fluid">
      <div class="circle--fluid--cell circle--fluid--primary">
        <h2>Projects</h2>
      </div>
      <div class="circle--fluid--cell circle--fluid--secondary">
        {% if user.is_authenticated %}
        <a class="button button-primary icon-on-left" href="{% url 'projects:new_project' %}">
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 13 13" style="enable-background:new 0 0 13 13;" xml:space="preserve" class="add">
            <polygon points="7,6 7,0 6,0 6,6 0,6 0,7 6,7 6,13 7,13 7,7 13,7 13,6 "/>
          </svg>
          New Project
        </a>
        {% endif %}
      </div>
    </div>

    <div class="grid-25">
      <div class="circle--filter circle--secondary--module">
        <h4>Search by project needs</h4>
        <ul class="circle--filter--list">
          <li><a href="{% url 'projects:all_projects' %}">All Needs</a></li>
          <li><a href="{% url 'projects:by_skill' skill='android' %}">Android Developer</a></li>
          <li><a href="{% url 'projects:by_skill' skill='designer' %}">Designer</a></li>
          <li><a href="{% url 'projects:by_skill' skill='java' %}">Java Developer</a></li>
          <li><a href="{% url 'projects:by_skill' skill='php' %}">PHP Developer</a></li>
          <li><a href="{% url 'projects:by_skill' skill='python' %}">Python Developer</a></li>
          <li><a href="{% url 'projects:by_skill' skill='rails' %}">Rails Developer</a></li>
          <li><a href="{% url 'projects:by_skill' skill='wordpress' %}">WordPress Developer</a></li>
          <li><a href="{% url 'projects:by_skill' skill='ios' %}">iOS Developer</a></li>
        </ul>
      </div>
    </div>

    </div>
  </div>

    </div>
  </div>
  </div>
{% endblock %}

mysite/projects/templates/rejected_applications.html
{% extends "layout.html" %}
{% block content %}


  <div class="circle--actions--bar">
    <nav class="bounds">
      <ul class="circle--pill--list">
        <li><a class="selected" href="{% url 'projects:applications' %}">Applications</a></li>
        <li><a href="{% url 'accounts:profile' %}">Profile</a></li>
      </ul>
    </nav>
  </div>

  <div class="bounds circle--page">
    <div class="circle--page--header grid-100">
      <h2>Applications</h2>
    </div>

    <div class="grid-25">
      <div class="circle--filter circle--secondary--module">
        <h4>Status</h4>
        <ul class="circle--filter--list">
          <a href="{% url 'projects:applications' %}">All Applications</a>
        </ul>
         <ul class="circle--filter--list">
          <a href="{% url 'projects:accepted_applications' %}">Accepted</a>
           <p></p>
          <a class="selected" href="{% url 'projects:rejected_applications' %}">Rejected</a>
        </ul>
      </div>
    </div>

    <div class="grid-70 grid-push-5">
      <table class="u-full-width circle--table">
        <thead>
          <tr>
            <th>Applicant</th>
            <th class="circle--cell--right">Applicant Position</th>
          </tr>
        </thead>
        <tbody>
          {% if application %}
            {% for application in application %}
              {% if application.status == 'r' %}
              <td><h3><a>{{ application.applicant.first_name }}</a></h3>
              <td class="circle--cell--right"><span class="secondary-label"></span>
              <h3>{{ application.position }}</h3>
              <td class="circle--cell--right"><span class="secondary-label"></span>
              <a href="{% url 'projects:accept_reject' app_pk=application.pk status='accepted' %}"></a>
              <a href="{% url 'projects:accept_reject' app_pk=application.pk status='rejected' %}"></a>
              {% endif %}
              </tr>
            {% endfor %}
          {% else %}
            <p>You have not approved any applications</p>
          {% endif %}
        </tbody>
      </table>

    </div>

  </div>
</body>
</html>
{% endblock %}

mysite/projects/templates/search.html
{% extends "layout.html" %}
{% load static from staticfiles %}


{% block content %}
<div class="circle--actions--bar">
    <nav class="bounds">
      <ul class="circle--pill--list">
          <h2>Search Results:</h2>
      </ul>
    </nav>
  </div>
  <div class="bounds circle--page">
    <div class="grid-70">
      <div class="circle--article--body">
        {% if projects %}
          {% for project in projects %}
            <h3><a href="{% url 'projects:project_detail' project_pk=project.id %}">{{ project.title }}</a></h3>
            <h4>Project Description:</h4>
            <p>{{ project.description }}</p>
            <hr>
          {% endfor %}
        {% else %}
        <p>There were no results for that search!</p>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}